# Course Description

This course provides an introduction to the molecular and cellular basis of life, the theory of evolution and the diversity of microscopic organisms. Four hours of lecture and a two-hour lab session are required each week.

## Learning Objectives

*	Identify the basic characteristics of life and outline the theories that attempt to explain the origin of life, as we know it and define it, on the planet Earth.

*	Identify some basic chemical concepts and apply them to the structure and biological processes that occur in living cells.

*	Identify cell parts, and demonstrate understanding of their related functions. Identify similarities and differences in the structure of viruses, prokaryotic cells, and eukaryotic cells

*	Explain the significance of enzymes, coenzymes, and ATP, and to identify the main events, products and significance of the processes of cell respiration, fermentation, and photosynthesis

*	Understand, explain, and contrast the processes of mitosis, meiosis, and binary fission in terms of their physical differences and their genetic and evolutionary significance. Explain the process of viral replication

*	Identify the structural parts of DNA and RNA, and understand how DNA directs the activities of a cell through protein synthesis, including some examples of how this process is regulated

*	Demonstrate understanding of how genes are passed from one generation to the next by completing representative genetic problems and explaining/applying genetic concepts

*	Demonstrate understanding of the three Domains of Life (Archaea, Bacteria and Eukarya) and viruses. Identify some of the distinguishing characteristics of each domain and the viruses

*	Learn and apply the laboratory skills associated with the objectives listed above

*	Explain the basic concepts of biology in written and oral form

*	Apply the concepts learned to better understand the biological world, and the problems that affect human society
